---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: adsbexchange
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: adsbexchange-secret
    template:
      engineVersion: v2
      data:
        UUID: "{{ .UUID }}"
        LAT: "{{ .LAT }}"
        LONG: "{{ .LONG }}"
        ALT: "{{ .ALT }}"

  dataFrom:
    - extract:
        key: adsbexchange