---
# yaml-language-server: $schema=https://raw.githubusercontent.combjw-s-labshelm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app adsbexchange
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      adsbexchange:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/sdr-enthusiasts/docker-adsbexchange
              tag: latest-build-846@sha256:642fc67b770312699cac12fee1cb1eca5e7569d394b8237be584d8dbf28af9e6
            env:
              BEASTHOST: ultrafeeder.default.svc.cluster.local
              SITENAME: PAdsb
            envFrom:
              - secretRef:
                  name: adsbexchange-secret
    persistence:
      run-cache:
        type: emptyDir
        medium: Memory
        sizeLimit: 64Mi
        globalMounts:
          - path: /run