apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rook-ceph-service-monitor
rules:
  - apiGroups: ["monitoring.coreos.com"]
    resources: ["servicemonitors"]
    verbs: ["get", "list", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rook-ceph-service-monitor-binding
subjects:
  - kind: ServiceAccount
    name: rook-ceph-system
    namespace: rook-ceph-system
roleRef:
  kind: ClusterRole
  name: rook-ceph-service-monitor
  apiGroup: rbac.authorization.k8s.io
