---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ultrafeeder
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: intel-device-plugin-gpu
      namespace: kube-system
    # - name: rook-ceph-cluster
    #   namespace: rook-ceph
  values:
    controllers:
      ultrafeeder:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/sdr-enthusiasts/docker-adsb-ultrafeeder
              tag: latest-build-635
            env:
              TZ: Europe/London
            envFrom:
              - secretRef:
                  name: ultrafeeder-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 80
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 50m
              limits:
                memory: 0.5Gi
    defaultPodOptions:
      nodeSelector:
        rtlsdrblog.feature.node.kubernetes.io/rtlsdr: "true"
    service:
      app:
        controller: ultrafeeder
        ports:
          http:
            port: *port
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
        className: internal
        hosts:
          - host: "ultrafeeder.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: ultrafeeder-history
        advancedMounts:
          ultrafeeder:
            app:
              - path: /opt/adsb/ultrafeeder/globe_history
      data:
        existingClaim: ultrafeeder-graphs
        advancedMounts:
          ultrafeeder:
            app:
              - path: /opt/adsb/ultrafeeder/graphs1090
      cache:
        type: emptyDir
        medium: Memory
        sizeLimit: 1Gi
        globalMounts:
          - path: /run
            exec: true
          - path: /tmp
            sizeLimit: 128Mi
          - path: /var/log
            sizeLimit: 32Mi
      additionalMounts:
        - path: /proc/diskstats
          hostPath:
            path: /proc/diskstats
            type: File
          readOnly: true
        - path: /dev/bus/usb
          hostPath:
            path: /dev/bus/usb
            type: Directory
