pull_request_rules:
  - name: Automatically merge Renovate PRs when all checks pass
    conditions:
      - author=renovate[bot]           # Only apply to PRs by Renovate bot
      - check-success=Flux Diff (kubernetes, helmrelease)
      - check-success=Flux Diff (kubernetes, kustomization)
      - label!=do-not-merge            # Skip if 'do-not-merge' label is present
    actions:
      merge:
        method: squash                 # Squash commits into one before merging