pull_request_rules:
  - name: Automatically merge Renovate PRs when all checks pass
    conditions:
      - author = renovate[bot]
      - check-success=Flux Diff (kubernetes, helmrelease)
      - check-success=Flux Diff (kubernetes, kustomization)
    actions:
      queue:

queue_rules:
  # If you have other queues defined, add this at the end so it is processed last
  - name: dep-update
    batch_size: 10
    # Wait for up to 30 minutes for the batch to fill up
    batch_max_wait_time: 30 min
    queue_conditions:
      - author = renovate[bot]
