pull_request_rules:
  - name: Automatically queue Renovate PRs
    conditions:
      - author = renovate[bot]
      - "check-success = Flux Diff (kubernetes, helmrelease)"
      - "check-success = Flux Diff (kubernetes, kustomization)"
    actions:
      queue:
        name: dep-update

queue_rules:
  - name: dep-update
    merge_method: squash
    batch_size: 5
    batch_max_wait_time: 15 min
    queue_conditions:
      - author = renovate[bot]
    merge_conditions:
      - "check-success = Flux Diff (kubernetes, helmrelease)"
      - "check-success = Flux Diff (kubernetes, kustomization)"
