pull_request_rules:
  - name: Automatically queue Renovate PRs
    conditions:
      - author = renovate[bot]
      - "check-success = Flux Local Success"
    actions:
      queue:
        name: dep-update

queue_rules:
  - name: dep-update
    merge_method: squash
    batch_size: 20
    batch_max_wait_time: 15 min
    queue_conditions:
      - author = renovate[bot]
    merge_conditions:
      - "check-success = Flux Local Success"
merge_protections_settings:
  reporting_method: check-runs
