---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app bifrost
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      bifrost:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/chrivers/bifrost
              tag: dev-2025-03-13@sha256:7813755f28ffd80ec2d467a200a3b3d7e7cc6f0bf3582f1d9a6cd3bff94bd463
            env:
              TZ: "Europe/London"
            # probes:
            #   liveness: &probes
            #     enabled: true
            #     custom: true
            #     spec:
            #       tcpSocket:
            #         port: &port 53
            #       initialDelaySeconds: 15
            #       periodSeconds: 30
            #       failureThreshold: 3
            #   readiness: *probes
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
            securityContext:
              capabilities:
                add:
                  - NET_BIND_SERVICE
    defaultPodOptions:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: *app
    service:
      app:
        controller: *app
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.0.0.68
        ports:
          http:
            port: 80
          https:
            port: 443
    # serviceMonitor:
    #   app:
    #     serviceName: *app
    #     endpoints:
    #       - port: http
    #         scheme: http
    #         path: /metrics
    #         interval: 1m
    #         scrapeTimeout: 10s
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
        className: internal
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        type: configMap
        name: bifrost-configmap # overriden by kustomizeconfig
        globalMounts:
          - path: /app/config.yaml
            subPath: config.yaml
            readOnly: true
      bifrost-persistence:
        existingClaim: bifrost-persistence
        advancedMounts:
          bifrost:
            app:
              - path: /app/persistence
      cert:
        type: emptyDir
        globalMounts:
          - path: /app/certs
