---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: bifrost-configmap
    files:
      - config.yml=./resources/config.yaml
generatorOptions:
  disableNameSuffixHash: true
