apiVersion: v1
kind: Pod
metadata:
  name: storage-debug
  namespace: default
spec:
  containers:
  - name: debug
    image: alpine
    command: ["/bin/sh", "-c", "sleep infinity"]
    volumeMounts:
    - name: config
      mountPath: /config
  volumes:
  - name: config
    persistentVolumeClaim:
      claimName: home-assistant
