apiVersion: v1
kind: Secret
metadata:
  name: openclaw-secret
type: Opaque
stringData:
  #ENC[AES256_GCM,data:l07nGSgD+xCUF6B8r4IVHYgz4VbOUIJK7I+Y9QY9BrkW/u9Qb/iad5E87UyLMDHV0Q/YcuSEEbhS/kR/X6fyuB0FREY=,iv:bbH+vKAOaN4ZsdLdJ/t6oy+5AOrmjV5qpAdbDT9sFRI=,tag:NoOVusyNtGnZXaLja35R2w==,type:comment]
  #ENC[AES256_GCM,data:SJxUaFpnJYij0St6U8TFNThtXPpw7ngpSG28Wq9EqXJ95oTbtau4qoJih32AeHDILUqwGsEiGXBeES6CjNzj+XvMghs=,iv:DQ88Rs5IKxt6XHBgvB8S34MG9l5n1HmEEWHInXuGClk=,tag:LkODJmYtZ+qst//F3UzG+g==,type:comment]
  OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:+/sCOzosnXLRVL55DxNy/lVSqFpiUVA7bZs5sNI7RDG5C2bRjNVsfRWqvPPKdU5/zgkEauKkwCaA84+WFjhsvg==,iv:+Jfw43b42gOIpcDkW47Nh9fezeo4TpcizUrCeyHIGTY=,tag:l1DhYxeg3V7MmoOLD3Me1A==,type:str]
sops:
  age:
    - recipient: age1pfs7k56cwml2ynecshxp02ktpx6kcsn3aq789rmzqr29xwt88y0s6ps9qq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1b1pGZ29PcU1JUjl6N1Jp
        WHlKOVdVandOalNwTFdnYW5EYnFEaFJvY0hVClpHN0s3WmxpTVI3Tjd3eWRGQTR5
        YUE5WFB5aEYweHhyNU9ZNkNRandNYVEKLS0tIEhRQmpGeTdUaUdCSzI3WXJUWTEw
        OFRSNE5mR2RnZWVlbFRVU05DTVJJOW8K5FJd4t7AKkp+TjwhBfCZqJlTmbZZRJ7i
        L2AiP5+a7tpLhwsfOPhzJCCEHKTSwO0cCUlMgsC238p3pD4UHoZE8g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-25T01:52:46Z"
  mac: ENC[AES256_GCM,data:ovit7rQ/K+Qk88YbEUmKJcsdLJEvJUZZdXnzN2LkkJmOCWX6efODMol2YfTvQZLCVreZe9AcdpC/fogZMuXbKo4zw6h114d126Q13wlEY+E/w/4iZQ7HX1fHvdwstPGlhgtuXfhttEX7AxD7skkKwesNlQ/wACUGycehaNyfY80=,iv:0pf7hHQczoGFo2IdZH5xjwUuM1g18gijQemhB2pk7co=,tag:/gWYaZCk0iJintci4uPt8w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
