---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zurg
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      zurg:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/debridmediamanager/zurg
              tag: 2024.12.26.0027-nightly
            env:
              TZ: Europe/London
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /http/version.txt
                    port: &port 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi

    defaultPodOptions:
        imagePullSecrets:
          - name: ghcr-token
    service:
      app:
        controller: zurg
        ports:
          http:
            port: 80
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
        className: internal
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: zurg-data
        globalMounts:
           - path: /app/data
      logs:
        type: emptyDir
        globalMounts:
          - path: /app/logs
      dump:
        type: emptyDir
        globalMounts:
          - path: /app/dump
      trash:
        type: emptyDir
        globalMounts:
          - path: /app/trash
      config-file:
        type: secret
        name: zurg-secret
        advancedMounts:
          zurg:
            app:
              - path: /app/config.yml
                subPath: config.yml

      # media:
      #   type: emptyDir
      #   globalMounts:
      #     - path: /media
        # type: nfs
        # server: expanse.internal
        # path: /eros/zurg
        # globalMounts:
        #   - path: /media
