---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: rtlsdrblog-v4
spec:
  rules:
    - # RTL-SDR Blog V4
      name: rtlsdrblog.v4
      labels:
        rtlsdrblog.feature.node.kubernetes.io/v4: "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            vendor: {op: In, value: ["0bda"]}
            device: {op: In, value: ["2838"]}
