apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:vf6+QmmZwbrDMewyg1H7P19RB9li/EioUYZrEXbqeE4Q1tEI,iv:1/qMaAPmhrgskZdDhj3FsjavJ+Les0njooVY339qaU4=,tag:YR3w9tWcr/gE7sakDzqWZA==,type:str]
    credentials.json: ENC[AES256_GCM,data:D+yMFbKzLZSLQYqcy+8VhbnP3gdscXCaHuSSYsJAkcs66gKT18BSQkTDBoodmdo38Kd2Pyiw/n66zxpavcNwowEtjasz69WOt4VOEryApCPs13lJllOyKcHA0GLtvR4FZ9txWmX72q57Fhf447AskUrZjUvTGGPowpCadB2bJZclqkjMNwctzo4Fx2Q1sy9+olLbKY/qYbsPOKa0KmoyptVY2m3QPcCvrXlFxlYzelgW4WPVH20NuWTuRQ==,iv:Qp8gp8q1V38m0OODyo7D/Bql2w7V//Q/gy3JEPiV42M=,tag:CpfBOvrq0LN5MsbIGWfK+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfs7k56cwml2ynecshxp02ktpx6kcsn3aq789rmzqr29xwt88y0s6ps9qq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQVFaMFdOcXJSc0tjUytk
            d3ZrdUlKMGl6L01ZNHYxWTRCNENOU3Rpa0dBCjhTenI1MVQrTnlNZ3JIVWxEYjFG
            QUROeS9sc08zZWhVRGUyMm5wbysyQlUKLS0tIERQZ09wcHBXd1NDdWdzUXRtaVlu
            NXJlR3JkUWdrQmV0L1RuN0V5OVdUYk0KXcf5HvrH9olcs0nsmdNx6Xq2xcA+jDOj
            1vGeJ6BjfsEjM6nn5suzTmHPtIZqxkc03k4TmJSQF02Z0KWuP4FP0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-10T08:09:36Z"
    mac: ENC[AES256_GCM,data:A27tva7bf/UddQbxH3vfpnqt9g+0AgvpZsUvW1PyrqQ9qU6zdKEqSkQgeV2AlRMIOSIpFM/9DZsXOnzyaFV9VmydfHRRRPlFUIY5DG1jocxx4w1FYA81dTimKuPwPd7ufOiCG5qKWF/l2YXd5kLNN2RtHl4Oax5VSxwKOOfmUFk=,iv:BBpiwHBaRofxrnWTNoJZOl2GUXiCC60oeUMI9eJHhjM=,tag:979cWpYtPa3edXrdPnCQ4g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
