apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:DOSDUn+IbQzhegMhPq3POKNFEuwmegICWSLB///At72+RX5sFiSEMg==,iv:gVmADRKO5vrht2WkyKSXGsjTMSvJp/DIwhW18zZDnHQ=,tag:fyzwMMFBwTGgSnPNiwNflw==,type:str]
sops:
  age:
    - recipient: age1pfs7k56cwml2ynecshxp02ktpx6kcsn3aq789rmzqr29xwt88y0s6ps9qq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RFUrS0ladmN0M0pxOUFm
        SVZEZEdtdXUrUGVlRHY0Q0ZnS2FSN3JyVTA4CnIwUjlJSFNjaldWNzk3d1h3TzR0
        ZWk0TVplOTNZNHVueU43eW1xOHhYK28KLS0tIDVqTXgwb01CYm9rMVl2YS9jNXA5
        bW5WdDhaaVdTaXpDUGtLZDFCeGZ3ZkkKj1sgvUuDq/nQdWYfBUtudR9J1UEcI4/v
        tkh00HdOfMTMOVj//Hv+cJZgcz5WDucpfvcK/k4mdM8l+4xB98k2ow==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T01:48:27Z"
  mac: ENC[AES256_GCM,data:D2Ip8n7wzPMMFCRJUqQ8A1nFbiwTx/7WojMcAsKDxxk1ucQDWuWKZqk0cerA7HNgcSYKRtUSecB+xi1SZpbGgFaUfAisxOO6MlsYea5Ru9VibhUa4/QtW465UEGkCbS2fKIhigrmkQSwxmPofliLy0TG8LQvZbkGFcwz1bbpgRA=,iv:CW+Wtr250HLZ+e9CVoSNEV8CFwV62aIXr0EeAKhONRM=,tag:8Ddk5tAP2i62uZ+hbPkkUg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
