apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:ljnncdAo109e/Q4dIa9XrrCVwGLArQ2osk3O83qZ7CF2SYOUlYr0hQ==,iv:LlPDBHIj0rz8VbLbST4Jbrq6Y5m1B0qrxBlGT4CAGYM=,tag:281yDd4G4/Bbz5tzn/DhAw==,type:str]
sops:
  age:
    - recipient: age1pfs7k56cwml2ynecshxp02ktpx6kcsn3aq789rmzqr29xwt88y0s6ps9qq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTUJOcVhDSUpGY1RmMndq
        RDVPQi9BVlBZOUNhTFdTSWZKZDJBYTdDaUI0CmdqcDBYRmtrVGlpVmhJRXJxS0s5
        Zjh5V0FSUXRNOUloVGpWRTlUcXZHa2MKLS0tIFNpS1ROcE1hK1JoZFFyWitxbGRC
        Slg2bERwNE5JeGhUNThxZGk0MUxUWnMKNrlgshvRQatgRP/wEm46F0jq9oWaBvwS
        me8bTEb0Za/LaiS34v4TdA35+lNsOm5a/4GdVkeu7OlTHKR0BoCUJw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T00:43:28Z"
  mac: ENC[AES256_GCM,data:cmxwtanTMji6gibI88Vo7BWdKHHtoRIy1t2KUpqymk27xR2HUqIJsxSrS1BbL0GZrXCAvCSkKyyq8nRJoHDfhmqtZIKwdSXet/iTf+XuZ/UGEdk+jYvJvNUUHr5W7+PFgb6R4PDn74dpRkQNcOHFd2PKI4VKeiW5PQfCW2DA/5g=,iv:bZLpcbt+Je8BZX34h9QvRZOx78vvNYhGQ7DZgTo7HBc=,tag:96Q1gAu8ESUnmm++W6XDvw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
