apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:criypn2CEza7X8PiY6buWj5UioLtzd5R0zm5P9VWWOI8yvuuqJI4aQ==,iv:zQwU5o4rntpWTKEj+ELT/g39XgKw9a4uP1ZsDyrYICk=,tag:ULl8MbDkullKB97tVHKfgg==,type:str]
sops:
  age:
    - recipient: age1pfs7k56cwml2ynecshxp02ktpx6kcsn3aq789rmzqr29xwt88y0s6ps9qq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONmFwZ01iazdyUGJ0OVQx
        OGFnUFpuajV2TFhQMjFHeWU2R0x3TUJkZzBVCko3RTUrNmhFYlFZa3cyLzI1M0Fm
        N00rS0I0N0lYMENXVzliZTM2aWpHWmMKLS0tIHZTT1U4MVZDQnpnd0hNbFpkUG0w
        MWxaUG55K0JMamd5MExwRUc1RlNsT28KInwDsFNxs7SV0R00GjHjRj75ya6RLhLJ
        2YEOU4uc0yRt/uOK+8fm88hJiZo5SuZImj4/xsJ2iDxgGLFfwpUriQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-25T13:32:36Z"
  mac: ENC[AES256_GCM,data:eXu//f9O2/kRe9pMhIvwD+F91jyU0DA8ffaHU7EHyexRcPrUWKYdCJG1Z92VRIh3ArAfm8NdpqnXI4LWFeMhnWJwhC/uaTAaEOPzSr0c7DNgbtFbpY/EBRpJoK0YBgZNfMkvKqnSCx+W5ZFzz6rwT34SCgfNxQ/lqOR3+fquGCo=,iv:k3klUL62FDkloPBhRvNz98pYJecqtFc6eoeWc1+Tzfk=,tag:g1PTor3FXDsPGF44NCF8ZQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
