---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flightradar24
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: flightradar24-secret
    template:
      engineVersion: v2
      data:
        FR24KEY: "{{ .FR24KEY }}"

  dataFrom:
    - extract:
        key: flightradar24