apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:GYBGy+XUDwnMTt4F,iv:2lRXDwRuxH8TG/OAmbTw//kF9g/GMcQ8NTydExpyz4I=,tag:FlJo3B4y+61uHSeuj3TsQg==,type:str]
sops:
  age:
    - recipient: age1pfs7k56cwml2ynecshxp02ktpx6kcsn3aq789rmzqr29xwt88y0s6ps9qq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbXcra2tTK0JIcHNZNFNq
        dElwOGl2QUlXMjVoYU9laTVqcTlJNTVCa2hJCkd6Tzl4VHZYenB2YTBXVXBIYmtS
        dEZBaVlsbCt6RTFxc0JxbFJwQW5PcmcKLS0tIE9TaXM1OFdDcUxjSTRTUk0vQ0Uw
        b1RoNWtZQUdweFMyWG1saUpuQ3hucjgKhdBB3aw5mlu37t04kTuHrxAkhUgYM0kG
        SnMth7qGt7cR6Hfg+MgXHcSVdVjFsqi0QesjVWxcgjh0zBHS6MrdzA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T01:48:27Z"
  mac: ENC[AES256_GCM,data:jQKA9T0aFS8JUphq81qNc3caLVWQc7qp/+ieRS5LU9e9nsCZeaB6t8PAdhL22qKlpELSrk3S5zorkdj2ZNvSOg3zcB1ogLbmQoXJQNOjTyRVWseEwTk9OMrKz6VoMMetQHM6WeDLVh3FDoEtC4zB++cZgO8G3bIEN5Rq6jdF5sY=,iv:JfWWxQRaWeuBF0BiiKyAQGOdf9SPEdjt8xu0yc5wUcg=,tag:TabzUbMKx4V7XUKPoct1kA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
