apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:Rb/z7eBol7yi20jo,iv:YcjyS+LB78J6tF0L7toblAnOrtLwy255rUrb4lw7CPw=,tag:gjBYgVPda7J1lPcXsE58/Q==,type:str]
sops:
  age:
    - recipient: age1pfs7k56cwml2ynecshxp02ktpx6kcsn3aq789rmzqr29xwt88y0s6ps9qq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxOVNZMHlWNHVuQUpVY0lm
        emYweW13Um42QVdoRkZML01IWHZkVDB2UERJCi9FMzhkY012cFVScGRvWFo0LzZl
        SCszYzlBRG95aFZmUm9LYWZJYVhMMTAKLS0tIGhxaHR5VEg5aUpJMGY5N0NNRm5z
        WEE0cXZlZkdiUDlLYkJESDZGNXdVVDAK+uxsr6N6G/F49WIpc8K0+2QB4nC0MDoI
        Yosk953yNS0TXJPQsgJBCqeCXJcXQFiWPWDwt/sTCMD7pEX4iERVDQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-25T13:32:36Z"
  mac: ENC[AES256_GCM,data:CMnZ+/gCbXfa6oQR10M4O3qCaBsx9SbeMl6p0Yy/IoeVxR/PA6c9C/MxQEHo2tGbE23fLEVNRwt4zdBdGfNXRJvXcRcoFEbX1aPuXrHxGicXbIbORBGiiPVHNwMSuamoJsit74VcYQfFnWG77ye+8hcXa91fx+hd6jjKtXW/yA0=,iv:hpHvywC2bzeolXDtKJ8WoEmHh05jG7p1w+h6ojL/s0U=,tag:qMmxM0fwj20OEaiI+MrUgw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
