apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:KBi6wMYkbfpT7FNK,iv:ETm/btr3HtgB/gR4CQIl4zw8SEJws43+NV1ScJ2Aa1w=,tag:Rvfn233ZDyuWZ9htNIPiGA==,type:str]
sops:
  age:
    - recipient: age1pfs7k56cwml2ynecshxp02ktpx6kcsn3aq789rmzqr29xwt88y0s6ps9qq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSFpocEdTRlZKLzdocXE3
        aFVaVHJKejZLRjF5VzZ1R3h6d2NyYk9ibVVJClliUzJ2ZVIwTXB6L1lYc21NYmo3
        di9vRGdFRmwzM3hNN0lNd3FtSWl1ZmMKLS0tIHIrMXcyczN1U3BWT3NkNVlvV0lh
        RndlRlNSUTZpM1I4SE1OdmIwc2ZoTEEKdFNDG1CNL2x47TNNjjWAd2j7Z5UxMwD8
        PWg5/BoUsamxqiSAoo0jxLXGl8kJApxh4/TlJbCF4jGzX6UQsxZ8ZA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T00:43:28Z"
  mac: ENC[AES256_GCM,data:StngJ3ZkLwLUVwnR9OnDpyjl+G2Ug7jUdlrMW23f82hbK1NJ1Uyaasdkipjvj9vkfyktCi1o04yg+535bYNnFYmpzeTnv2WG60Y+geFYdyzT1vg7AJu4KOhzCR3yc5C1CSKwF7hm1KWn29wXTlmaJcUSAA7p7A5TH9KqtBhYi4k=,iv:6ere/r50E3jTB6EjdMOtfAouVVGTlmlv4lzqSAoz+X8=,tag:p8xhAjwQn8I9kCA1L4W+xA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
