---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sparkle
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sparkle-secret
    template:
      engineVersion: v2
      data:
        PUBLIC_DISCORD_CLIENT_ID: "{{ .PUBLIC_DISCORD_CLIENT_ID }}"
        SERVER_DISCORD_CLIENT_SECRET: "{{ .SERVER_DISCORD_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: sparkle
    - extract:
        key: cloudnative-pg