apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:0ygwR/PSpjhU1qtwAdeEupi2qyeh6OYK++BXailmtcA=,iv:PrjNPctNp6DfNHEA80HeojO70b+W3HlGMjgWh+frgyc=,tag:OqX5pRU2VTudhHwz2BH0hQ==,type:str]
sops:
  age:
    - recipient: age1pfs7k56cwml2ynecshxp02ktpx6kcsn3aq789rmzqr29xwt88y0s6ps9qq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUc1hoaCtVNkZ6aHY1WHR4
        QkN0WmVuYXhDK2J1YWxEWFFDbFlWUlBUMW5BCkdwb2xFUGM1eGxPMmhHODlwVW85
        SjMrb3JoQ2o3eDlTUkdaMWkvd0xlRk0KLS0tIHgySCtQc1U0ckZrVUxkdWJOdnk3
        UUJLSWo3MTRvTWhiSVJERnF6UFBnV00KlEo+7CY4tEFEKPfm++DflBje6Z2YuaSZ
        BMltD0w5hJMFU63IL7/jHpEEMTAKujHcrFKI3YQOlrNiis4d3F7P8Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T01:48:27Z"
  mac: ENC[AES256_GCM,data:wf/ruxktsQ08BYiSubNhkTQF1feVb39998BfR3jBTg3ukg931ucaaac6Gmf/51/Hl/TvmKHpj0iijrVC+JqMk+WOrus01mV1cldn40PwfgJEC8akGrmvyquP0wzSPMLXIhbUstqy/DtAayLjGlzbCAV9n15Fl3B+RQ6pNrJVXl8=,iv:T+drr4LiI6OeED12NQmGr0KHkog+w+u5IHsiajT/9Fw=,tag:FC3rljBrYWKUujb7lAH82A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
