apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:UjGFZQSUk06XG6fEL1CMsZzyQJFE4mpbY+clNQFVcKk=,iv:Q1+in+L/LF3RH5QO7w8ClE9z3eDB+v8DabQgWPnE8Bk=,tag:rhHwWaFwAgtbGDMLdY8zhw==,type:str]
sops:
  age:
    - recipient: age1pfs7k56cwml2ynecshxp02ktpx6kcsn3aq789rmzqr29xwt88y0s6ps9qq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOExGZmZValhZblNOSXVv
        Y0R2bWw1U3dpdDR1NzRleFhXT0JBRlZwUjBnCi9qTmVJcTFDdjVWbzRwSlZKeEhJ
        L0hxMVk0NSs5YVVidk5QTTNvVGtYY1kKLS0tIDQ4bUZqUjJ3aGlBRm1URzlFTVgy
        d28rR3ZLTFZsbXNLMkkrdjVKdVYySzQKGWOMD9dJJqKvtlS7W+zOcbMMdacE9j9k
        AnYsfmyNcrYggs2honuKSbCU4JDsbsfgFuSIH10M6g7LqdEyTIHeLg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-25T13:32:36Z"
  mac: ENC[AES256_GCM,data:XXGWzu8cZGNJp3jdtFlmu8KkaHnD543rFaYd1k1njdR/Gi2K2ut7A5xOXHSktb+uihYbNoSNMLoMRW9u10fswZeCDS/dFllKdJYnfs7HVQ3uuaBiyjPqfttdaDroa/xMR5WRG74Edx8Io1qyz8zXUywcheOhH5HnloAYVAgG5KU=,iv:z2YsjZ12nE4XBJ1YNCuaXBdRNBeVAhqKwe6O/+KG6v4=,tag:DwDE8WhaIIXmDKC3R1uf6w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
