apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:qgf577UQxB0y40m3EwGuFirGUcqlzSVVNbDym0jIHos=,iv:A0KwqJ7s/BC2G4zNpLNjP2g5XhvFJ2oRAmH9MPnwegI=,tag:VU873017hqoj/ke6KwReKQ==,type:str]
sops:
  age:
    - recipient: age1pfs7k56cwml2ynecshxp02ktpx6kcsn3aq789rmzqr29xwt88y0s6ps9qq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQU9YaHlKQ05mZDJXV0FM
        czBERWJ5emdzaVNLc0FBb1grUW02aFlTU1VNCldXZ0xQVE9GV0JFaGNlRVRQMkR0
        cGkyZVVvVUNrMGdiQ2xQZE85UzVSajQKLS0tIC9OL2cwcmdvd0lUTDR1L1lZeTdC
        cEJQK1drT05wVHRPM256TlA5Yk4wZTgKUvJp5cwUq4Xt6ksY6iEPs9dnafD7a5md
        vjAjxbry+vkT5J8wlRxeAsVUJEeG3Cn4mdDW9Zx2BkP57tkmwvzF/Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T00:09:12Z"
  mac: ENC[AES256_GCM,data:UaPrxJpqkmKc8I7qxwKXWYrH9X3VXVpWGw99U6k/RqnSOVaiYRUgLgsckiWy8bBoNuTlMVQFqFlBvrbFtmXBAL1juJzOZuCx4Df+8zMBlA8C/MqB6BlCiOy6VxjsX4W0gN0mGnhadBbQCc4ZwRDwzIUf8FZSBuAt9w7dd0G+S5k=,iv:8en3er0+XYdyEtkGTEERiDMt2vrvSrNuzNBSD+TAsAo=,tag:hssK4Ky3bygPZFJiqZBtxQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
