ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy

detectors:
  coral:
    type: edgetpu
    device: usb

# model:
#   width: 300
#   height: 300
#   input_tensor: nhwc
#   input_pixel_format: bgr
#   path: /openvino-model/ssdlite_mobilenet_v2.xml
#   labelmap_path: /openvino-model/coco_91cl_bkgr.txt
mqtt:
  host: emqx-listeners.database.svc.cluster.local
  topic_prefix: frigate
  user: "{FRIGATE_MQTT_USERNAME}"
  password: "{FRIGATE_MQTT_PASSWORD}"
go2rtc:
  streams:
    reolink_doorbell_front_door:
      - ffmpeg:http://10.0.0.2//flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_REOLINK_USERNAME}&password={FRIGATE_REOLINK_PASSWORD}#video=copy#audio=copy#audio=opus
      - rtsp://{FRIGATE_REOLINK_USERNAME}:{FRIGATE_REOLINK_PASSWORD}@10.0.0.2:554///h264Preview_01_main
    reolink_doorbell_front_door_sub:
      - ffmpeg:https://10.0.0.2//flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_REOLINK_USERNAME}&password={FRIGATE_REOLINK_PASSWORD}
      - rtsp://{FRIGATE_REOLINK_USERNAME}:{FRIGATE_REOLINK_PASSWORD}@10.0.0.2:554//h264Preview_01_sub
objects:
  track:
    - person
    - cat
    - dog
record:
  enabled: true
  retain:
    days: 3
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
cameras:
  reolink_doorbell_front_door: # <--- this will be changed to your actual camera later
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_doorbell_front_door
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    motion:
      mask:
       - 0.243,0.01,0.732,0.002,0.727,0.067,0.237,0.067
       - 0,0.147,0.471,0.389,0.473,0.461,0.542,0.485,0.529,0,0,0
version: 0.14