ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb

# model:
#   width: 300
#   height: 300
#   input_tensor: nhwc
#   input_pixel_format: bgr
#   path: /openvino-model/ssdlite_mobilenet_v2.xml
#   labelmap_path: /openvino-model/coco_91cl_bkgr.txt
mqtt:
  host: emqx-listeners.database.svc.cluster.local
  topic_prefix: frigate
  user: "{FRIGATE_MQTT_USERNAME}"
  password: "{FRIGATE_MQTT_PASSWORD}"

go2rtc:
  streams:
    reolink_doorbell_front_door:
      - ffmpeg:http://10.0.0.2/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_REOLINK_USERNAME}&password={FRIGATE_REOLINK_PASSWORD}#video=copy#audio=copy#audio=opus"
        #"#video=h264#audio=copy#audio=opus#raw=-vflenscorrection=cx=0.5:cy=0.5:k1=-0.290:k2=-0.012"
      - rtsp://{FRIGATE_REOLINK_USERNAME}:{FRIGATE_REOLINK_PASSWORD}@10.0.0.2:554//h264Preview_01_main
    reolink_doorbell_front_door_sub:
      - ffmpeg:https://10.0.0.2/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_REOLINK_USERNAME}&password={FRIGATE_REOLINK_PASSWORD}
      #- rtsp://{FRIGATE_REOLINK_USERNAME}:{FRIGATE_REOLINK_PASSWORD}@10.0.0.2:554//h264Preview_01_sub

review:
  alerts:
    labels:
      - car
      - cat
      - dog
      - person
  detections:
        labels:
           - car
            - person

audio:
    # Optional: Enable audio events (default: shown below)
  enabled: False
  # Optional: Configure the amount of seconds without detected audio to end the event (default: shown below)
  max_not_heard: 30
  # Optional: Configure the min rms volume required to run audio detection (default: shown below)
  # As a rule of thumb:
  #  - 200 - high sensitivity
  #  - 500 - medium sensitivity
  #  - 1000 - low sensitivity
  min_volume: 500
  # Optional: Types of audio to listen for (default: shown below)
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
  # Optional: Filters to configure detection.
  filters:
    # Label that matches label in listen config.
    speech:
      # Minimum score that triggers an audio event (default: shown below)
      threshold: 0.8

detect:
  stationary:
    interval: 50
    threshold: 50

objects:
  track:
    - person
    - cat
    - dog
    - car

record:
  enabled: true
  retain:
    days: 3
    mode: all
  events:
    retain:
      default: 14
      mode: active_objects

cameras:
  unifi_back:
    ffmpeg:
      output_args:
        record: preset-record-ubiquiti
      hwaccel_args: []
      inputs:
       - path: rtsp://49.13.69.116:7447/s9W4Z6RD7fH1xpOE
         input_args: preset-rtsp-restream
         roles:
           - detect
           - record
           - audio
  unifi_front:
    ffmpeg:
      output_args:
        record: preset-record-ubiquiti
      hwaccel_args: []
      inputs:
       - path: rtsp://49.13.69.116:7447/DnXU3hLaZp2vj3sU
         input_args: preset-rtsp-restream
         roles:
           - detect
           - record
           - audio
  reolink_doorbell_front_door: # <--- this will be changed to your actual camera later
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_doorbell_front_door
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
    motion:
      mask:
       - 0.243,0.01,0.732,0.002,0.727,0.067,0.237,0.067
       - 0,0.147,0.471,0.389,0.473,0.461,0.542,0.485,0.529,0,0,0
version: 0.14
