---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aiostreams
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: aiostreams
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      aiostreams:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/viren070/aiostreams
              tag: v2.31@sha256:26d93653c3a5d0835db9189d6aca21d05614e68107c4d4a3ec7196b60c88c3bc
            env:
              TEMPLATE_URLS: '["https://raw.githubusercontent.com/Tam-Taro/SEL-Filtering-and-Sorting/refs/heads/main/Tamtaro-All-Templates-for-AIOStreams.json", "https://raw.githubusercontent.com/Vidhin05/Releases-Regex/refs/heads/main/all-templates.json"]'
              TEMPLATE_REFRESH_INTERVAL: 3600
              WHITELISTED_SYNC_REFRESH_INTERVAL: 3600
              SEL_SYNC_ACCESS: all
              WHITELISTED_SEL_URLS: '["https://raw.githubusercontent.com/Tam-Taro/SEL-Filtering-and-Sorting/refs/heads/main/AIOStreams-SyncedURLs/Tamtaro-synced-ESEs-extended.json", "https://raw.githubusercontent.com/Tam-Taro/SEL-Filtering-and-Sorting/refs/heads/main/AIOStreams-SyncedURLs/Tamtaro-synced-ESEs-standard.json", "https://raw.githubusercontent.com/Tam-Taro/SEL-Filtering-and-Sorting/refs/heads/main/AIOStreams-SyncedURLs/Tamtaro-synced-ISEs.json", "https://raw.githubusercontent.com/Tam-Taro/SEL-Filtering-and-Sorting/refs/heads/main/AIOStreams-SyncedURLs/Tamtaro-synced-PSEs.json", "https://raw.githubusercontent.com/Vidhin05/Releases-Regex/main/English/expressions.json", "https://raw.githubusercontent.com/Vidhin05/Releases-Regex/main/German/expressions.json", "https://raw.githubusercontent.com/Vidhin05/Releases-Regex/main/English/legacy-expressions.json"]'
              TRUSTED_UUIDS: 223e1a26-472d-43d9-9da3-bac6b6802cd4
              WHITELISTED_REGEX_PATTERNS_URLS: '["https://raw.githubusercontent.com/Vidhin05/Releases-Regex/main/English/regexes.json", "https://raw.githubusercontent.com/Vidhin05/Releases-Regex/main/German/regexes.json"]'
              PORT: &port 3000
              LOG_LEVEL: info
              DATABASE_URI: sqlite://./data/db.sqlite
              BASE_URL: &url "https://aiostreams.${SECRET_DOMAIN}"
              BUILTIN_STREMTHRU_URL: *url
            envFrom: &envFrom
              - secretRef:
                  name: aiostreams-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/status
                    port: *port
                  initialDelaySeconds: 50
                  periodSeconds: 10
                  timeoutSeconds: 10
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 18m
                memory: 128Mi
              limits:
                memory: "3Gi"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: aiostreams
        ports:
          http:
            port: *port
    route:
      app:
        hostnames: ["aiostreams.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-external
            namespace: network
    persistence:
      config:
        existingClaim: aiostreams-data
        globalMounts:
          - path: /app/data
      cache:
        type: emptyDir
        globalMounts:
          - path: /home/node/.cache
