apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aiostreams-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: topolvm-thin-provisioner
