apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:6zkonhEZLebG1F/FLHGIpXPvWn5FWTW2QILIbqtFAVlypvV37tHMbg==,iv:wk0zhn8eqKAiTz4TI2fecBpG2oHl0fR9ENorjg1NyD8=,tag:I+JTHo+EaA/ztrJdU8R3bA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfs7k56cwml2ynecshxp02ktpx6kcsn3aq789rmzqr29xwt88y0s6ps9qq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UnNrS21yMjA5elJYa05s
            d2ZOMVBIb3ZxQlhvZW1WcGEzTVd1SDRWdVN3Ci9tc0Qvb1dzN3pTQ2I2RjZpVjFu
            VWhWMFFLQnM3R2dRNnJRSWNMeU5IRXMKLS0tIFp4aTJSaEJmR3c3QXhxaWdsTHBx
            b093bkNVeXYrWERRejRJMFg4ZVpSMUEKC4nhHKvkAs95D+m/gMCMf1V4eVzamrGs
            i6ytjrmNEqeV06uev6quyEqrbb8atvXKYathQDQcN2ZoYnguARcB3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-16T12:59:24Z"
    mac: ENC[AES256_GCM,data:LLRO8Jjr1o72TBN/GcLEv3J54IB+IM/ZQ1cns613CGftODlA9XGXoGGRIIM8ZJwN6KX8xAE2qzXMSlp/2HiMFpGeY5at9QZoLt4SP6QQxtlV6QrzUtXrmbS0Cwc2hCzCGoYfi7NSW3xeturIhRlDoVNKwAMwf6PA8FYAq94ONrE=,iv:01InmVxvxmuyqH7CgbAA2FeUjWWl39sbUJDhQrXcuVc=,tag:hnucezf83lzyP6hyDEXKtA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
