apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:iuEroFzOrRaOZksz57u39ainEsKT5Ot/BFs7uKNfI7Eb6ClrGboTaw==,iv:aGecvOhkhP4d6cU1ijUUvcdTSlY5disXnMgqM872ENY=,tag:dI6+iPnNhECgGp9h3v9e4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfs7k56cwml2ynecshxp02ktpx6kcsn3aq789rmzqr29xwt88y0s6ps9qq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWWRwMENZRFhiNjdMQWl6
            aGVEQ3p1WWpuaGw0Sy82K3hLQjB5UG9USkJvCnhZUmgvTlpNT1NRbGVFcGdhTEZl
            MStpak5vSkRHeG9JT3MzRGx4emZIZFUKLS0tIElsVmZwWEdHbHVzRFR5ZDB1d3B5
            MW1BRmNCbkszM2kwa3NKSVlFWmw3RWsK5NGlf0xR2CNzK5YamJ+0lftbXI0yIWfu
            lqhi31hSazBTx/zJwFtRiBJh44MxTfVA62vSjV4yr/nAygMoCBwktw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-10T08:15:29Z"
    mac: ENC[AES256_GCM,data:runn5VxVDLlWtSQDr6auL7hPXRZ3RuWcTqJrsEpHwCspQyUFGIJ0Lf7B/eYIaXv3jLu520t+pFIu4eBJGgcjXFdzGoYu0wLPtd234zMaEFezvGMn9tSk5V8FBRay7FYruLKcbyx0FL+d0Px2dy/fizEZT+/4zXTluXR4lWEwE88=,iv:SIkLuCWORdR+qiODkCI6LJIbu5Y68zBo0Hxd96z9/p4=,tag:i/otbwCgyVJ2hILvYz49fg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
