# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.0/charts/other/app-template/values.schema.json

controller:
  main:
    strategy: Recreate

    containers:
      main:
        image:
          # -- image repository
          repository: vaultwarden/server
          # -- image tag
          # this example is not automatically updated, so be sure to use the latest image
          tag: 1.25.2
          # -- image pull policy
          pullPolicy: IfNotPresent

        # -- environment variables.
        # See [image docs](https://github.com/dani-garcia/vaultwarden/blob/main/.env.template) for more details.
        env:
          # -- Config dir
          DATA_FOLDER: "config"

# -- Configures service settings for the chart.
service:
  main:
    controller: main
    ports:
      http:
        port: 80
      websocket:
        enabled: true
        port: 3012

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  main:
    hosts:
    - host: chart-example.local
      paths:
      - path: /
        pathType: Prefix
        service:
          identifier: main
          port: http
      - path: /notifications/hub/negotiate
        pathType: Prefix
        service:
          identifier: main
          port: http
      - path: /notifications/hub
        pathType: Prefix
        service:
          identifier: main
          port: websocket

route:
  # -- Enable and configure route settings for the chart under this key.
  main:
    parentRefs:
    - name: gateway
      namespace: gateway-namespace
      sectionName: gateway-section
    hostnames:
    - chart-example.local
    rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
      - kind: Service
        port: 80
        name: main
        namespace: default
        weight: 1
    - matches:
      - path:
          type: PathPrefix
          value: /notifications/hub/negotiate
      backendRefs:
      - kind: Service
        port: 80
        name: main
        namespace: default
        weight: 1
    - matches:
      - path:
          type: PathPrefix
          value: /notifications/hub
      backendRefs:
      - kind: Service
        port: 3012
        name: main
        namespace: default
        weight: 1

# -- Configure persistence settings for the chart under this key.
persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
    - path: /config
