apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:apcry17r7oz47AJLqiwFZjJZu+2Sp5ifE2f82dYQNQXsMd4LU4KVUdaJt1IiGs5ZPhEoXTQrkkfhPFG7muuO22QDNvxyhEaw2oCIcRvKEMBFmD8611PUA8ZFAAu3T91F5/lFWiOwuj2zkCXz7t9ivQqc57WQrJhwHovb9iuSGnQODQhZlCeyC2b8DMIeRCEOxb2lP7As8b/4gcjQZ+zsG/9GIZRUpb0EmUPe0wmNBaLW3dOE,iv:TEz6YBbuBICXNBzSUpVHHPp/GhlJrS2EQhAlqACFb3w=,tag:LHO70F/QIjnMLeRDaLshvQ==,type:str]
sops:
  age:
    - recipient: age1pfs7k56cwml2ynecshxp02ktpx6kcsn3aq789rmzqr29xwt88y0s6ps9qq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVE9oN3ZDRVprdEc4eFAy
        aTZLSmdJK3ZvZW5meUlxK1oxNFFZNHFSc0Z3CmY3R3YzWngxWDFaRzVGZEJMK2o3
        QVVXRC8yRUFpQ1dsTFZOQm1SUnZGOGcKLS0tIEpNTTdJM3Y1cEpMcTNOS2xtWSt1
        M0lBb0lISXFuaEtMLzZOOFdNRkU0QUkKyKpKTP9irroiIQua4NKQeHK/rN2nCPcG
        UxPq9RFwJkOPsxs/OCMv3NZyCDEsKXpZPjTr2cwT1ykG6T2yriseyA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T00:43:28Z"
  mac: ENC[AES256_GCM,data:kWlquicigxU/QFkif3Eugs/PZ1QVZL5rXYmMpjq8j2aGOuY/nMeLDerP6ueJQ1GakaOqDZ4pUl6bcXF4QesB8Q7wckQKH3jt2nfWky+An43ijcR6+gxYqE5S6H7eI9/OFGP5VDpKhehrlBrZKeDridSs5HoSaH2FoBZYidPiBMk=,iv:jnfjFe0OExrgoXLtAD7I56HbZ0rVxPzwSXpjTQmjU6Q=,tag:gWkna8h9t3+YHcAOhJRnTg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
