apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:lTvXB+m923HaaG6vcRH+QF6vFAjSIZbGmw2LQaYPPSsDLYOH3X6ZkCR+z5eLbl6b7AhkYKlOZdPjJxFHZA1em0bEmzkxQLmUmklD1BoT4daME4TOyejMLfzN6ZG2ODR9ldvulolVjdpGDJsoVLPAynyrz9OUhJrhEblhvwwFCZTlw5N24GJzZ4PLlbsxLyMnK+aToi+j2WJEL6Xza/zbt+i+1ZqK+e2p/KMKWwXPuRtL78Dx,iv:3iMtRjFP7z2RfqMckkdlzp0QTpNSBJga4Qd5yHllKCk=,tag:YcksjP5XCocdFc4gNo6xjA==,type:str]
sops:
  age:
    - recipient: age1pfs7k56cwml2ynecshxp02ktpx6kcsn3aq789rmzqr29xwt88y0s6ps9qq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVldzaHFNdDJvWC9jMHk0
        UWxEMi9aTnpyTldMZFhMMXdEdHhJcUxwekVBCmFYQy9OZURKWVgxNDY4all1NVU3
        eC9FeFZZQjF5cmtPaWwvZ29nK3V1YTQKLS0tIGJBaU42VnFYTUpxajcvbmo1RDhn
        bjZBY2VhVXVkZnNBaTlQNmd2Q0ZOencKTYDSIjSxy3XNEUarSnQIa27tmDxyuwYT
        6T8cMobfisMMUQTDkRJaOz/w5pzB4HyB6GOTO6XmxvIYO76lZ5yUng==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T01:48:27Z"
  mac: ENC[AES256_GCM,data:KSOyZZef6RCYtVcKNMGKkcnFxx/gBrhU1r10TjtpDFrbO84QFkH/Uq6q1R53ZC1mRPpVgqRC7+vpjU1XrQh4Pm32I+N+ioHdCCamTbI495OjgkYiIEAOIGBcvd74xOUXEQ8aRMJI9DdcaY+z0be3LsQZkPAv11bFYXU7VFsl32I=,iv:vvJyQTEYW05uqroZFGx1228ozcTahcD929ZC8GKfaDc=,tag:ioVSBQETLf8Dirhv1rzusg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
