apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:m+ggherhLOfJhg09jI3fLHXF7kCpm+/5IhWJWZJ3rQPvPI9u91hMUrG5kjeW1RZy2EU+8ajH9gHZZOJvhitBwQBEztw/RIw0T3rWk/JmlLnAn0/spyCbkZsqlMm8KEHtFtaIFUe23yTLEq5H9Oydwz7fyDdz94G63mMi4FgD/+aRo9Wne5t+0xL6KDCScJTUxIYtNBoaxCXhHOXTmIsRaR7UHJKgxHK+g4GjPZSAmSu3rXSE,iv:vGfCdHKZja8pkM2Rr4QSf16I5pmRXM6fg/hU+KRvuHM=,tag:klcpQsprSrR6m+VAR6QXlg==,type:str]
sops:
  age:
    - recipient: age1pfs7k56cwml2ynecshxp02ktpx6kcsn3aq789rmzqr29xwt88y0s6ps9qq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZ2ZwdUcycnd1cDdidE05
        cUdhU0FZcm9rT0lwQlZ1Y3NvYkdyNFZpMFhFCmloMTI5VXRzOWF0K3dEaVpQVVRi
        bEtrSVFTelo1TzVZVkt2RWJWZzZPQ3MKLS0tIHhQVERiVDZnc2NrRDF6Vy9MYUEy
        N283R01jcS9VbG1PT2Q2cG1PamcweDAKHI9w8eOZeJ/5N8AjAlg20Mq2BT7IcZBf
        6MP5zn83G0tQgvKEi9V+bN9+tSQB3kfACLwCCvBPHshbuzS27pxCSg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-25T13:32:36Z"
  mac: ENC[AES256_GCM,data:R8vTTg/uQwt7QKi5mfwh01t/juHBI+CrtBkaFNgg+a/gUB0VrlWBPjaQp5yotf8ThVfAixIt3Adm5bmGbeZwKbuZpKb/dr2gkh0cAFiPAmJnTpkym0vpwzeLq7o3Z2bC+sq6JR0QNZKBYjw5VgX7MKqcuGcVM6JgE6Cq8INVCKs=,iv:69RNE9sypqt0ira7c7qbf+REx9dZx08FnFQiIWnacbQ=,tag:mYCSAEZf6QBGgTLph+aMQg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
