apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:6uEJSDYafaq6wFthkSnIpxMBWOlxp2e8xaOypAPqRYAa5WLnIJjuhw==,iv:BI8VXcUXFkcY9zaU5eBMFTOaEFbQ4DKBpAYQ+8zvK/U=,tag:TWtIAw0+ZvSiJy4hC+nh5Q==,type:str]
sops:
  age:
    - recipient: age1pfs7k56cwml2ynecshxp02ktpx6kcsn3aq789rmzqr29xwt88y0s6ps9qq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNaVAxS1R1V2JPaVZvbHhh
        ckZLV1c2SEdRbGc3NXZ2VDFXVEt5QkRobkcwClBDOG0wc0o0QXVKcllPK3R1Sm5H
        Z05haFdaMHF6aWZKU2pvaWI3MzdLQjgKLS0tIC9wYmdNc0hUNGliZVdmTlVjL01D
        Zk16UE1uY3ljVVN2OWlqYWN2d1IwVHcK58CxcTubn0y3JXRtWf1X5W/KlSjCuagv
        XVaZRmspSSekFdX7zKlwDd0xoZ/cS8Oh56e6caieKh1iqtvf7n1zag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T01:48:27Z"
  mac: ENC[AES256_GCM,data:Ci7hDaoSl64Q7nJmGHtsI+KJoF6mHnrqeqstNtasgBxUHdF+Gp1vkMBbt18CaxB3NnaxGYnTkJdmhiG8YChWbb4l1oKXmwp6wte/l14d0wyAm6xkpCtLhdek4gzfn/Y/hIzwafvPKLazDj6TcXuVcMH7DM8DrxS3LOlQqn8Ge40=,iv:M3lCb5aY4tuJWM+gju4c9uiOPaboHLdE+R9VAkpoqPA=,tag:cCNicWIOBWYKm2BTkzYmng==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
