apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:pEZSSfV5CmvyRwc67Nr6SjPYlzxa4IgPSPIBRyvhaGtfODvGttuj+g==,iv:efrzBfVKyW2a/Qt2W70RUhOV0KGCkSB8T0dbaTtrWNQ=,tag:mXTFQ5PCcin4pppM1JkhvQ==,type:str]
sops:
  age:
    - recipient: age1pfs7k56cwml2ynecshxp02ktpx6kcsn3aq789rmzqr29xwt88y0s6ps9qq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIS3BZZmtaaE5naWV4YWxL
        N3BWWUpRWFN2T2Fzck1UTEVqaEUxRk5sV1RNCkxXaW5WSDdNZVdHNDVmRzZrc0Nq
        R082djROUVRtY3hDVzQ3Z21FWkh5aU0KLS0tIGJKZEZOckZjdmY2VlNwS053K1V4
        UFhQVUt5TmJQSXgvazk2Y0E4ZWJLZ3cK4XkXALIu5xZZPH1pBBgHEQ5Tftq78DKO
        VzK+rGHwFKfGjCUZrhHDFUCShVUb3EN4f8FD+1/aMDHwoHSO4ha5og==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T00:09:12Z"
  mac: ENC[AES256_GCM,data:6NjDUT9/ZpOf9FimRlD+uzkq9nH8g3K2EYkk15fE72FhOjIsUmahnNtwJLDbAAdQvbPfL/XChlQpnP7+B6j2dMrpJuPyulri8lZ/heiDjARYt2T7ywc5hbrdR8nmKuzPlu+gCuq4XGxrqBoGPsCGqdvj4EMYKFlSQ/0nvBi+C4o=,iv:gxdGrH9MfMydvPlO2zRKFYa4p1bIg2ETX9kMRUAp4BA=,tag:2NcOrGJns+pb/+e3Iamrpg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
