apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:k5hqnJpmPR+OEQhaBIUXW9Npf81qq21l2gOGkLoLt2FM8ABsIHsTHg==,iv:xQAgMu6JxemuxZ+9RWnfHQ79P7d9Q9SWJITE/A6tOlY=,tag:f9jENx1fCZP6cBjUEv8b0A==,type:str]
sops:
  age:
    - recipient: age1pfs7k56cwml2ynecshxp02ktpx6kcsn3aq789rmzqr29xwt88y0s6ps9qq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RFhFZkphRjVWRzU5c1h0
        ZmhkdGZ4aERRKzRKNEg1T0kzSnBGbTgxYldzClFTUGJjeGdUaVZTUGM5OXc4WFFl
        OUhhVFNlME1YSTBIRVAvZys2MXdENVkKLS0tIERydUkwOEdjdmFsdmF6UG5IdEJK
        Y0tRbDNUWWg5VWF0Q2pobDRQMFh4cXcKOvf6hoC9U5aepuxJYumAFTqQS5IyTrb4
        NOur880jXf1O6C6bu7An7IbyHS63PoK+TV5SavD+5DdP2jdw8sE50w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T00:43:28Z"
  mac: ENC[AES256_GCM,data:uamH3XWJhltNQu/KstUpL3A59NP/HVbuPkuSfSD9F3T+OLjDQ9BruMnkmvksrwImEGluyNnFxKuFPmITGv7z+k0RmcflB2wXZd3d4+Uq6wCFxilLNYT7lss6xL60r2BAzKtyITfJrlOi2/WopBtt3GWon+OwOsbI2QUY/I7thFw=,iv:SxN5F6+UcJpnZ76JC7wARM/+6Xn2xg6k3HFcJZt7Dlk=,tag:Pj2j5FNXEW/EliLueHho1w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
