apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:7uHc0L+kya55goiM,iv:huKjjf5H+BUN7WHFjsS+cRp/DMDW1b7k2V/TD2jr4a0=,tag:TLtlbPDRtVvjJg/3o3M0kA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:edfErbwUjv+PtphN5X7+06g=,iv:afnSuMFMohc7ba1/7+IQw8gO/7GJP2b9A6xlnmm7URQ=,tag:KW71ciNOIdygngjJghWVDA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:MyeXVKwSRLVEPmS055Eg4xgwqKw+LzqZP05sC4Xpq8RSOniB,iv:LXcZ/tXJYg7QRxs60+30Z9bvAK56Yh5ac1bxGUsgSys=,tag:j8PU81Ftb5bACMNYMaXiHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfs7k56cwml2ynecshxp02ktpx6kcsn3aq789rmzqr29xwt88y0s6ps9qq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdHdaaWpYbUNOdnRwWHZP
            bVNPZVlCWkg2cnRzVEprUU12SXJaWHhXZ2pzClFBY0VhT203cXYrU1VSR1JKbVky
            and2QUdMK254dmF1V3NCY3hPV0wzbWcKLS0tIGExTnZCNEltdkJUVmJIUFZ5eWoz
            ajhtQlkxbTVwSzFKMHMxdzFlMHlGd1UK1uS376PmVHlsqh3m2g9PSuS0ja3wjoXm
            lkAVvIwuaAwRWTSH7M5b4triB9SjU1i1XYraK5k8RVo/CDbp/3zWOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T15:57:49Z"
    mac: ENC[AES256_GCM,data:5KhC0Qdkdb/Nsh+faf7T3da4onkHafYtNPIX6hopi+nDi2UkAoKQbumznl5HzIiZSNSWJfN69bJTCcwA8tOj6hmL4G5zF/soMcf62ra4zY0i/YNgLaf4soGieLF+8Ue6/vRYOVZv64OnJOltSDwSIrlENrYQhwmbD0WKqip3WCE=,iv:AWj+BY81KTvbrdA19p/vFxICcCqNLVt3l+mjUqa0AH4=,tag:5hn+uCQQP2KUtT4pdmwJ+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
