apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:UIV+5U0xWnbhKnNS,iv:CJlkqdS+zsGl7V+mj1PnrGlyFnAVg6UUMBwF0Wtv6Xs=,tag:xM9zxQFzPdOMW3Tdgb7AyA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:8wRPxCEg8CCX2Ditq+tx+Ck=,iv:mdW79BdyJtuZ0Nbhj3Wqwg3/IB6waslsdf3wtQ41nxA=,tag:zMJFAE6wTRbYUU5Fyd5R1g==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:4P6yAhIyQkbSeG2dfqzFINaJpIpucX8KFXbTgmQoaODNNO93,iv:qD4mZutOfMHDsIw17czpe13fhsl2etbkZj7S25bZKmc=,tag:H+n0oapplOH3cVChC9096w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfs7k56cwml2ynecshxp02ktpx6kcsn3aq789rmzqr29xwt88y0s6ps9qq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2blZpTVoxSlB1dU8rQWl0
            d09UNnVZVWVyKytOL1VLVFY4RFYzYURwMDJZCmVLNllRbUM3d2diTWdEOGFueFBM
            Nm1JeWlKd0IwYlZFS2JqQU5iWXcrVGcKLS0tIE9iMVQ2MkV1WWZQdldvVXdiZW9D
            b1lIK2dNLzJrdCtkTEVkSE9WbVdxTFkKiqSFuH8pdkxssuSu8nrrltduiqygCEY+
            R84GPLmtXKHetK/p+7kiBikAR5dJxALbTVxwd3+qDeRfYVWeucWyUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-16T12:59:24Z"
    mac: ENC[AES256_GCM,data:nOwRflhCgl/ZlGpjmrmYoEPZzsjTBNrtLVFMinpvJuOs+q2HlLoPdVVIPEW2U4rWoncn6Yb+437Yw4eXDJc4ucUtVNxpqYQcd9UfVyPYx76ctSypbU8BI4E6lJJq8f+K/8APOMkZBS5A/DTn7GyvX5DYd7D+E1RCr67/Zk8Wo7s=,iv:v17byYwwrV4EtPKOLvSFj4XErUwz7YagbM1/vKRXuhc=,tag:QmUMU1cfqwx83DZu3sIgKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
