apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-web-ui-config
  namespace: flux-system
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: ClusterSecretStore
    kind: onepassword
  target:
    name: flux-web-config-secret
    template:
      engineVersion: v2
      data:
        config.yaml: |
          apiVersion: web.fluxcd.controlplane.io/v1
          kind: Config
          spec:
            baseURL: https://flux.${SECRET_DOMAIN}
            authentication:
              type: OAuth2
              oauth2:
                provider: OIDC
                clientID: {{ .CLIENT_ID }}
                clientSecret: {{ .CLIENT_SECRET }}
                issuerURL: {{ .ISSUER_URL }}
                scopes:
                  - openid
                  - profile
                  - email
                  - groups
                impersonation:
                  username: "claims.email"
                  groups: "claims.groups"
  dataFrom:
    - extract:
        key: fluxoperator