apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:lv/076BhKC9Z35drj5a4m0ow6DjXRn7F6ikR28I8cR8=,iv:L7iimlubqwYESx0q/2w/Tt+zh6qz89lzZUU4DcPk/ok=,tag:FmV9rv45TKdVQrYz0fAxLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfs7k56cwml2ynecshxp02ktpx6kcsn3aq789rmzqr29xwt88y0s6ps9qq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MWZzNkNCQU9Za296Y2pL
            eVByTCtuRnluUmU5cVNNL2hnWEowVytiSDFvCktuckgycnBJMzNmekV5TWVVd1M4
            amg1d3B4OFJZT0lDKzJDenpxWDZqQ2cKLS0tIEFVM2JrOGtnZDRVV2ZGUU5vYzNi
            N3dHR2VOVHBNelN4K0gvaHJpQjQ4ZWsKXnP3gVkHFKnsNTkuU2E9Uv/h7lq3twvK
            xg/iO2xfdQSxrdmA9YJdJpm1HZuqJs0JgeAhUOfKrTn4gF0sJlQrNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-16T14:19:42Z"
    mac: ENC[AES256_GCM,data:kGRyFLE3Rvq/1KBpT2XtMYWaTnAKwWa7q6OUw92EPtYwsnKUcsPCfMY5Wb6UBRQBv7KbYejehPcUjpIP9aqKEmSP74mm8DPbfG/0XVSjHlajum6oMSMelrT+eNRNwpEmNuX2BsXWm7DO4k+bKezjJR5LwO1Kq0SiCQI+8KE2Jrs=,iv:1frivY3yHgVtSNhapQJHUfh+CavLmjNha+HxbBD+fe8=,tag:6Wbm73E9QJVUwEs4lrtWDg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
