apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:xGZ2o1esAADfIAvTeCXfj0OQeMol707z3oOJSEhEEy0=,iv:Ll66l0KCpLTRD/riFRyzD+cjQssI2K38CkLnxuxUYBE=,tag:Iq2G7nRSs8yYPyTlR33poA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfs7k56cwml2ynecshxp02ktpx6kcsn3aq789rmzqr29xwt88y0s6ps9qq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrYVR4dHliUitYT2hBanZI
            ZjVBeVhIVkJ3d1RIWUJNMG5JLzdlN0wxdFNzCjlJTmFGSy9ZZ0JUMlhxWk45d1ZM
            aFpaQU1BVGVhOWNKT2luWmY4eUVwZ28KLS0tIGt1SEhPNmd1Ni8wVlFFVnIwZmRW
            eE5MVUNpNTJjR3BZSVRxMzE3andub0UKzD+WFBkAL2cabUxIekq62oX4bKsyeVx6
            9Dbt8+TJKIact4oG/AzFR9MjnrKxDVO2zalRcXkMWMyfalfavwZ9MQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-16T14:18:25Z"
    mac: ENC[AES256_GCM,data:m0kTdjXKroSOFjeDDBWCumtcNbOpX5vkrHWTg6uKvqfBkO9t4Wf/JQEt9UjUPZRnIgr6JHwl37JS0JcdmIdKyYYKmVFG0H5eMdnb1Goe4kiY/sHhRq7nsw/yM2SAMVV/9MfxrA9I2DcwSmZcZTse+ZKfTUKhDKGi+M47k6xCpSs=,iv:kYqzz0xlO2avAazCxWuotxmzD43Z3AtkC8Gd4exSog8=,tag:3i2Bf2x8FTtB/j+CdjV8gA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
