apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:VuS/JO1Ddbf3/81IBsYS4rhtt78P8WJa2/q9m2mMnLk=,iv:XZumUEIepvG7nvkcKXIqZ1exUIwNyIap/3npTv0AtcU=,tag:NnhyTJ/pMU1+1JxQGxuZkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfs7k56cwml2ynecshxp02ktpx6kcsn3aq789rmzqr29xwt88y0s6ps9qq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSWM3ZEQ3eDM4djBaZXdO
            VXZlUk11QTREbkNkMXRYNGpIZEtTZDRTeEc4CmJ3SHM0NmFwZEFxZE13d3JpOXNn
            dkZtYXhkQjBtZlpLT2xLRk1aNHJCbVUKLS0tIHVxUFo5ZzVPTmg0N1E0RUxTZEtn
            MmNya3ZYUm05cG03Y21FeWJqb0p0YVEKEBMpLUAjiQNfQEfyEliwgF2hCqJImanW
            83X1XDeH/fus90uXKY6korsWCC+apzIJnw/O4nLLxhLdwZMGL6ngQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-18T13:21:17Z"
    mac: ENC[AES256_GCM,data:hQe0CGL/j1A03g48KEvAt1KfvHUrdLhVFplqrVKncP3TWP32UoNTozkUvMK3/LZDZ6V4PeGuCx7Xc9y7D4TVSWDXAA5/jVEk8G/uAIRTYu6WGvGeKqizxDSMd3mQCn+Koch1w/xnEXYLntibBy/Wlzsm4VGyjc7AaC9Pi4LhrLQ=,iv:s+y77u411kePdaCQ+MoVZOgiGlwuEQmB59y+XBYqzjI=,tag:VhLm22FQBH4Hvy53G5feSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
