# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frigate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: frigate-secret
    template:
      engineVersion: v2
      data:
        config.yml: |
          mqtt:
            host: mqtt.{{ .X_EMQX_DOMAIN }}
            port: 1883
            username: "{{ .X_EMQX_MQTT_USERNAME }}"
            password: "{{ .X_EMQX_MQTT_PASSWORD }}"

          gotortc:
            streams:
              reolink_doorbell_front_door:
                - ffmpeg:http://10.0.0.2//flv?port=1935&app=bcs&stream=channel0_main.bcs&user={{ .REOLINK_USERNAME }}&password={{ .REOLINK_PASSWORD }}#video=copy#audio=copy#audio=opus
                - rtsp://{{ .REOLINK_USERNAME }}:{{ .REOLINK_PASSWORD }}@10.0.0.2:554///h264Preview_01_main
              reolink_doorbell_front_door_sub:
                - ffmpeg:https://10.0.0.2//flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={{ .REOLINK_USERNAME }}&password={{ .REOLINK_PASSWORD }}
                - rtsp://{{ .REOLINK_USERNAME }}:{{ .REOLINK_PASSWORD }}@10.0.0.2:554//h264Preview_01_sub

          objects:
            track:
              - person
              - cat
              - dog

          record:
            enabled: true
            retain:
              days: 3
              mode: motion
            events:
              retain:
                default: 14
                mode: active_objects

          cameras:
            reolink_doorbell_front_door: # <--- this will be changed to your actual camera later
              ffmpeg:
                inputs:
                  - path: rtsp://127.0.0.1:8554/reolink_doorbell_front_door
                    input_args: preset-rtsp-restream
                    roles:
                      - record
                  - path: rtsp://127.0.0.1:8554/reolink_doorbell_front_door_sub
                    input_args: preset-rtsp-restream
                    roles:
                      - detect
              motion:
                mask: 0.243,0.01,0.732,0.002,0.727,0.067,0.237,0.067
            version: 0.14
  dataFrom:
    - extract:
        key: emqx
    - extract:
        key: frigate
