---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frigate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: frigate-secret
    template:
      engineVersion: v2
      data:
        #from emqx
        FRIGATE_MQTT_USERNAME: "{{ .X_EMQX_MQTT_USERNAME }}"
        FRIGATE_MQTT_PASSWORD: "{{ .X_EMQX_MQTT_PASSWORD }}"
        #from frigate
        FRIGATE_REOLINK_USERNAME: "{{ .REOLINK_USERNAME }}"
        FRIGATE_REOLINK_PASSWORD: "{{ .REOLINK_PASSWORD }}"
  dataFrom:
    - extract:
        key: emqx
    - extract:
        key: frigate
