---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: click-log-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: topolvm-thin-provisioner
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: click-log-clickhouse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: topolvm-thin-provisioner
