apiVersion: v1
kind: Secret
metadata:
  name: click-log-secret
stringData:
  #ENC[AES256_GCM,data:X8+BD3DD7xusMcgpI11mvYiKFvxCyckHzWF7i5aNkdTD1C6xnY5UGdlWoN8bWQNI20Ga65M9YPdGluSrhciVwy+gspRW5g==,iv:kNJobITCDChpDcMRaT0+17j2M1Wx7OORKLEjATu0SEQ=,tag:Cf3lWOwaSrPrqnF0Dn4c0w==,type:comment]
  INGEST_TOKEN: ENC[AES256_GCM,data:jQqRwRNwdAqNGgbwyLP848zZReZYPV9OsryZXTqMYQnqbjo6TfBgXDYKCjmMIvcqcGnKYkPlJ7ajQWMzNeXzuQ==,iv:EswwbUH6oDsKaqMydI+KcUYvBNViBI8CmabJPDiiOX0=,tag:XEVVcpUjlIJpt+TE9x0x5A==,type:str]
  READ_TOKEN: ENC[AES256_GCM,data:pxAyf0NoP0ImZZ+IKct2o0yVA7UkC2BfNnilF1Q2d607W7VdfVHI7RpR5hiF9lXSLsUSfqeMy/FapWdy8uy4Eg==,iv:2apzjcnv3oa1HGUGfj87A25ObsuIDC8NmdPWX55o2lo=,tag:Ad2ciTvrjxo+9qLqV7i8kA==,type:str]
sops:
  age:
    - recipient: age1pfs7k56cwml2ynecshxp02ktpx6kcsn3aq789rmzqr29xwt88y0s6ps9qq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dUNOZk1SQlBnamFHdkUz
        YlRLU2h6LyszWm9PclBqOHdtTTZXdXJzWWx3Ck9ma2RqaXBDNVFKZTJVZko3aEow
        d3dqeDdqN25RaFB3Z1pFOTRlVUxxeW8KLS0tIFdhT0M1K25RNlgzYkkraUpqQ2RG
        alpPZldGVzdlN1o5eUpaaW1JZkt4ekUKeOGyU5RkatNu7Y8REM2Ya6MH+LMZ0FVV
        g37ZT4Ba0QlUSammckTxrnTN/Xe5A18Ll5IOZ3CCQu3Qx/wmamaPzQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-10-06T09:35:18Z"
  mac: ENC[AES256_GCM,data:tXRbgV9UPiVOBG4GvHujumiIHaI1J3aEl6QSdszMS7YZBvwkZZkzXy9oPtmzhrH/upsQS56meR80NmtAalkuJPNPCoZYaxRT3x111IJCi1QCADLuxpNvaANP3+KnOaxCTbaMc+pVRHXE07xg7Q0O2pmvcdbllSmig2PQDg6VsiE=,iv:93iO6MksWyHWaI6W2lK3QDnLGQP55r+RjDY42wWBF1Y=,tag:ed8Xmy/dBeDd9OSI9ZGbBw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
