bifrost:
  # Override the default path to the one used in the docker image
  cert_file: "persistence/cert.pem"
  state_file: "persistence/state.yaml"

bridge:
  name: Bifrost
  mac: 90:e2:ba:56:b7:d0
  ipaddress: 0.0.0.0
  http_port: 80
  https_port: 443
  entm_port: 2100
  netmask: 255.255.255.0
  gateway: 10.0.0.1
  timezone: Europe/London

z2m:
  server1:
    url: ws://zigbee2mqtt.default.svc.cluster.local:80/api

rooms:
  bedroom_group:
    name: Bedroom Main Light
    icon: bedroom
