bifrost:
  # Override the default path to the one used in the docker image
  cert_file: "certs/cert.pem"

bridge:
  name: Bifrost
  mac: 02:79:63:E0:BA:CE
  ipaddress: 0.0.0.0
  http_port: 8080
  https_port: 8443
  netmask: 255.255.255.0
  gateway: 10.0.0.1
  timezone: Europe/London

z2m:
  server1:
    url: ws://zigbee2mqtt.default.svc.cluster.local:80/api