apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:fCWfsXvxefkJO0RkErh1fw619MAYgkpQvofXqIgPwu348qKmC+V9ow==,iv:0gOVoG1w5LnSRNAGDt3ttyCnU4Hv11jDTB2fSNphbBI=,tag:dGkTpHBxjrIhEXt1ing1oQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfs7k56cwml2ynecshxp02ktpx6kcsn3aq789rmzqr29xwt88y0s6ps9qq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQVF0U0VNRDRnUDRTM2pi
            MVROM2pvcWg2ejBITWxoZ3ZsUkRoSWxKRXl3CjhyWXRLQjdIVFFVRVY4djl6RUVI
            SWRmSy8xTjhBcUNBbU9BQjBZMFVDSkkKLS0tIDBsc2p6eG5yZEhOZEtWY0FBekVo
            dzM4bFM5SUdnZG9vUFhnaFlsYjFvcncKj3yV6P0z6GJ64VymvTk/7Vx0a04Zu6C6
            pVAPNt5nKpai6hvdY6nML9icHKxxB7qEIahc31KKA4Jpsg42L6Gt/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-16T14:18:25Z"
    mac: ENC[AES256_GCM,data:wjJB6OiXlashIsihj4ganKgEAns7ww4nTqG6L7nIsScRDmaxyqKNfidZ/d/wzVLhWN+nkKL6q3gZ2vMoPjpax5N1vqNSzknAWqmiAFKk7LzbizZAbcqBlEzKC+vWOv9gU/8CBDC9+hiJbi1D8QjlsU3DTcDA2ay1AMxVWi+/7iw=,iv:iV5l+U5SsvlfVBzcxblioqtK081SHugKultDeVH48ho=,tag:GfMaV1SKUKJ9zQQSHKrCxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
