apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:E3ElaqQ5UkdrKtTq0QFD9UxcUTuGGbgGbWAueHy7/tRaxYCGE6NuHg==,iv:3IqPLgjD0qwgNXqzPRwuqP0Km/Zx6z1ncKqkhcvwo0s=,tag:lBVo/0kqP0j+yQpOTMibeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfs7k56cwml2ynecshxp02ktpx6kcsn3aq789rmzqr29xwt88y0s6ps9qq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZjNNekRkY1NmVElMN1Jv
            NzZnZWt2dTNYaW4xL25RcUxaOVJRNEZxRUFrCkpVL0todkFYQkVTNUcwTEdPMHRY
            cUVnTzVxcmZnS3lsQjkzUGFlWGxjUTAKLS0tIFJ5dHVHRVJkR0c5TFlBbVJhYURM
            dTh1Y2FTbVcwcVcvSkxwM1FjbEx1WU0K/L9RUvK9YXNV0cRWh6erOgS26xFn8R4u
            pjyRO4SjfUC/nZ8uAxEjRKTPYUbw7qCf28sBTZA6COUX6tNBtN5m2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-16T12:59:24Z"
    mac: ENC[AES256_GCM,data:khouzSht1184SHkuA8ens5Mjso54ZqJiKELQQs7dP6Pj8IZeRsxPkmdocvbotYOX/SiItDo6uILHgq/Pf8gzSkOFumJbQiQ4FKsTYUbXEqZ4lAEZA8tDQ+ZPZl+wN36Z00GsPfIoQ2KRWZzJpQ+doHIsNlnQ5EjK+mi1lXh79vI=,iv:vE9r6KNFNOhAiOiK9qzBaasAWhvVHeZllyW8Zplt4zo=,tag:/weqD22ljUH0tZqT39n0Hg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
