apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:0WkAI64kFch0xYIkVbeqC8Gvfg7gyI2Fvp7ImKzbZC93ISt72sqzjA==,iv:3PP3fzWvrBSGiiMJprBaYFk1DfoLhHgkmt3COCy8xPo=,tag:NHQftWRWr7y7L6xRhYAWlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfs7k56cwml2ynecshxp02ktpx6kcsn3aq789rmzqr29xwt88y0s6ps9qq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WkpwYng2TC9HNnZ0bGdx
            OXhJWU9BQ0FZY3k2SitGQUVNZFJBTHFUT1M0CjBFNzQ0c0dKU2dKWnpGaFFkQzNS
            Nm5OTlRYT3diVXFPcGNMTjBPakQ0aUEKLS0tIDFiZXRMUHBvdkFOZ1gzYXBPb29w
            MCs3QURDTkJLclE1VWRlR0JTcmFvN2MKrD27o37V74bj00b5g3yGxshOSa+nrLpi
            w3HD40uIsy4XPnxFsNHcFLFrQgI8hHl+9pdOaftPtPE92R9FFJyDDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-18T12:42:26Z"
    mac: ENC[AES256_GCM,data:5T5d8OnG1kWcXC063MXO5I70XWDz+eRshVYw0oMiMJf/I62xD0vVC7TtWjrCpdlLl61d7l5GkxnDeLMKcbfpm8cbL8jvMimXsCeNy8anetl1qsDkeYf1I35bOMfDa+z44yVf/W2+1gosjk5SSRAf9UOQsV3LtXD7vFDUQEm93SY=,iv:qvesm6IItqMxQ6UfklLnhUWcSF+DsVa3qs51nCh3m/Y=,tag:57Kb9vF3YuR1y1Yw2R0MUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
