---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aiometadata-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: topolvm-thin-provisioner
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aiometadata-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: topolvm-thin-provisioner
